### ISSUE TITLE
(unsigned-byte 8) subtypes not allowed for stream types

### ISSUE THREAD

**Issue by ralt** [froydnj/archive#12]
When using `flexi-streams` to create in-memory input streams, archive chokes on the stream because of this check: https://github.com/froydnj/archive/blob/master/archive.lisp#L121-L122

This is because flexi-streams subclasses `(unsigned-byte 8)` to create `octet`, with the following declaration:

```lisp
(deftype octet ()
  "A shortcut for \(UNSIGNED-BYTE 8)."
  '(unsigned-byte 8))
```

Manually adding the check in archive, as such:

```
diff --git a/archive.lisp b/archive.lisp
index 7a5b3fb..208b0c2 100644
--- a/archive.lisp
+++ b/archive.lisp
@@ -119,6 +119,7 @@ requirements about alignment."
        (transfer-stream-to-archive archive filestream)))
     ((typep stream 'stream)
      (if (or (equal (stream-element-type stream) '(unsigned-byte 8))
+             (equal (stream-element-type stream) 'flexi-streams:octet)
              (equal (stream-element-type stream) '(integer 0 255)))
          (transfer-stream-to-archive archive stream)
          (error "Stream has invalid STREAM-ELEMENT-TYPE ~A"
```

Works.

But of course, you're not going to add this :-)

So... it's not exactly a subtype... but it kinda is.

What do you recommend doing? I don't actually know how to handle this in a sane way.

**Comment by froydnj** [comment]
The test should probably become:

`(and (subtypep element-type '(unsigned-byte 8)) (subtypep '(unsigned-byte 8) element-type)))`

**Comment by ralt** [comment]
Follow-up in #13
